### ISSUE TITLE
MQTT cannot login

### ISSUE THREAD

**Issue by Ondrashek** [octal-ip/ESP07_Growatt_SPF_3500-5000_ES_Monitor#4]
MQTT Broker with Home Assistant not work with your firmware gives me:
error: received null username or password for unpwd check

I see in your code MQTT Login, but it looks like your firmware want to login to mqtt anonymously, which is not allowed with mqtt broker in home assistant

I used this from a part of otta code and it worked just for one connection.
MQTTclient.connect(MQTTclientId, mqttuser, mqttpassword, MQTTtopicPrefix, 1, 1, "{\"InverterStatus\": -1 }")

**Comment by octal-ip** [comment]
Thanks for letting me know, authentication has now been added to the code. SECRET_MQTT_USER and SECRET_MQTT_PASS in include/secrets.h should be updated to suit your configuration.
