### ISSUE TITLE
Adding additional params

### ISSUE THREAD

**Issue by charun-za** [octal-ip/ESP07_Growatt_SPF_3500-5000_ES_Monitor#6]
Adding additional params like Battery discharge current, when pulling from the battery

much like the  AC_Charger_Battery_Current

`{"AC_Charger_Battery_Current", 68, 0, 0.0, RunningAverage(avSamples), 0.1},`
 
 would something like this work?
` {"DC_Discharge_Battery_Current", 67, 0, 0.0, RunningAverage(avSamples), 0.1},`
  

I'm guessing the Register name and MODBUS address....etc... any idea where to find this? 
  
Alternatively;
I suppose I could do a sql query by taking battery wattage and dividing it by the voltage 

```
SELECT battery_watts / battery_voltage AS Current
FROM growattinverter
ORDER BY datetime DESC
LIMIT 1;
```

**Comment by octal-ip** [comment]
The Growatt SPF doesn't have a [MODBUS register for battery current](https://watts247.com/manuals/gw/GrowattModBusProtocol.pdf), so as you said, you'd need to derive this from the Battery_Voltage and Battery_Watts values. Ideally you would source all information about the battery from your BMS, though, as it would be more accurate.

A small modification to the code in this project could provide the calculated current value, though it would always be slightly inaccurate as there's an inherent voltage drop between the Growatt and the battery that gets larger with the amount of current flowing.

**Comment by charun-za** [comment]
Thanks appreciate answering/confirming this. I did look through the register as well but didn't really find what i was looking for kind of weird they dont expose the register for it, as it does show as a value on the led display on the inverter itself 


As for accuracy I get around 50mv drop on negative and around 60mv drop on positive with a 50amp, battery, load between battery and inverter, so around 3~5watts loss, which I think most of that is because of the fuses (2x125amps) so its not too bad of an inaccuracy, but yeah not 100% accurate as you say but, imo its fine and it "used" energy
